# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapreduce.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmapreduce.proto\"&\n\x04Text\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x10\n\x08metadata\x18\x02 \x01(\t2B\n\x06Master\x12\x1d\n\rinput_spliter\x12\x05.Text\x1a\x05.Text\x12\x19\n\twork_done\x12\x05.Text\x1a\x05.Text2;\n\x06Worker\x12\x16\n\x06\x64o_map\x12\x05.Text\x1a\x05.Text\x12\x19\n\tdo_reduce\x12\x05.Text\x1a\x05.Textb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapreduce_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXT']._serialized_start=19
  _globals['_TEXT']._serialized_end=57
  _globals['_MASTER']._serialized_start=59
  _globals['_MASTER']._serialized_end=125
  _globals['_WORKER']._serialized_start=127
  _globals['_WORKER']._serialized_end=186
# @@protoc_insertion_point(module_scope)
